version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: realtime_chat_app_and_threads_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-realtime_chat_app_and_threads_app}
    ports:
      - "6450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
